---
driver:
  # using docker to test
  name: docker
  socket: unix:///var/run/docker.sock
  use_sudo: false

provisioner:
  name: ansible_push
  playbook: ./test/integration/default/default.yml
  sudo: true
  chef_bootstrap_url: false

platforms:
  - name: ubuntu-14.04

suites:
  # suites found at /test/integration/$test-name
  - name: default
